name: model-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - pytorch
  - torchvision
  - pip:
    - azureml-defaults==1.47.0
    - inference-schema[numpy-support]==1.5
    - transformers==4.30.2
    - pillow==9.5.0
    - jax
    - jaxlib
    - flax
